name: sourkanji_mobile
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  # Routes and DI
  flutter_modular: ^4.4.1

  # State Management
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1

  # Http Requests
  dio: ^4.0.4

  # Font policy
  google_fonts: ^2.3.1

  logger: ^1.1.0
  dartz: ^0.10.0
  freezed_annotation: ^0.15.0

  flutter_native_splash: ^2.1.1

  # Local Storage
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  intl:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner:
  freezed: ^0.15.0+1
  json_serializable: ^6.0.1
  lint: ^1.5.3
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.6.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    - assets/images/
    - google_fonts/
